### ISSUE TITLE
When Final Results come? And Could you compare TiTan V to RTX 2080 TI? Thanks.

### ISSUE THREAD

**Issue by clhne** [lambdal/lambda-tensorflow-benchmark#1]

**Comment by stephenbalaban** [comment]
The final 2080 Ti benchmarks are posted here:
https://lambdalabs.com/blog/2080-ti-deep-learning-benchmarks/

We're adding the Titan V and 2080 soon!

**Comment by matthew-z** [comment]
@stephenbalaban Hi, if my understanding is correct, this repo does not contain anything about fp16, right?

**Comment by chuanli11** [comment]
@clhne 
Please see this new post
https://lambdalabs.com/blog/best-gpu-tensorflow-2080-ti-vs-v100-vs-titan-v-vs-1080-ti-benchmark/

**Comment by chuanli11** [comment]
@matthew-z 
We will have an article about fp16 performance very soon. For now you have find some sample results in this post:
https://lambdalabs.com/blog/best-gpu-tensorflow-2080-ti-vs-v100-vs-titan-v-vs-1080-ti-benchmark/
